### ISSUE TITLE
Typosquatting website

### ISSUE THREAD

**Issue by DAGAMES386** [Vencord/vencord.dev#52]
Heya, I have no idea if this is the right place to submit this, but there is a typosquatting website calling itself "vencord.app" [(vencord.app)](https://vencord.app/). It has been detected by virustotal as a huge negative so there's that. I'm sure this is probably somewhere already and I just forgot to check somewhere, but it's using your logo to impersonate the team.

A bunch of people have reported it already on virustotal, but here's the link 
https://www.virustotal.com/gui/url/e256e2724b0cd1280684552561546ad5dd381115aef9e314a7d17a33b2ebad27/detection

**Comment by MrDiamondDog** [comment]
We're aware but we can not get it taken down

**Comment by Vendicated** [comment]
unfortunately there's nothing we can do about them, because at this point they don't break any laws (such as copyright infringement or spreading malware)

there were other impostors that spread malware, those were always taken down within a day of report

what we have done to limit exposure of this site:
- mentioned fake sites in our faq https://vencord.dev/faq/#What-are-the-official-websites-for-Vencord?
- added a warning in the installer only to use the official site
- added it to the ublock origin rules so ubo users will get a warning

sadly that's all we can do :( thank you for reporting it though
